### ISSUE TITLE
gurobi license not detect with custom GRB_LICENSE_FILE

### ISSUE THREAD

**Issue by julou** [fjug/MoMA#36]
when trying the fiji version of MoMA on our centOS server (where we usually run it from the command line), I ran into the problem that my gurobi license was not detected despite GRB_LICENSE_FILE being set correctly (but the license file is not gurobi.lic in the home directory).

Would be nice to use this variable if the default file is not found before raising an error.

**Comment by haesleinhuepf** [comment]
This issue hints to a more significant issue in the background: If you run MoMA standalone from commandline without Fiji around, our gurobi-installation routine may not work properly in any case. The user should install gurobi on his own (and we should consider documenting this properly). 
Furthermore, if the installation does not work properly from command line, the checking for the license makes no sense at all, because we only do this to check if the gurobi-installation needs to be executed. 

Suggestion:
* We don't check for the gurobi licene file when running from command line. 
* We adapt the online documentation to hint people to how to install gurobi.

Any opinions? Did I miss something?

**Comment by julou** [comment]
I works fine now IMHO (MotherMachine_-0.10.9-SNAPSHOT.jar)
- if gurobi is available and no license is configured in MoMA, things run s\moothly
- if it's not available the user is prompted to configure it
- from the command line, it's a reasonable requirement that gurobi is installed anyway
