### ISSUE TITLE
Better parameters for HEADLESS mode

### ISSUE THREAD

**Issue by fjug** [fjug/MoMA#5]
- [ ] allow to configure export options

**Comment by julou** [comment]
configuring export options should be possible in normal mode as well (probably by setting parameters in the params file?), because a given user is likely to most of the time use the same options for a given project…

**Comment by erikvannimwegen** [comment]
Explanation:
This is currently minor. It is just a hassle to always have to remember to change in the dialog box which stats we want to export (because they do not match the default).
Related to this, if the export stats could be defined in some parameter file or on the command-line, this would also allow us to run the headless mode (which currently we cannot because the default export stats do not match the ones we need for post-processing).

**Comment by fjug** [comment]
This can be implemented very fast and should be done at the same time with #17.

**Comment by julou** [comment]
implemented in MoMA's properties
