### ISSUE TITLE
Hyperstackreg considering only an active ROI for registration

### ISSUE THREAD

**Issue by fjug** [fjug/MoMA#8]
Have hyperstackreg work only on a subset of the picture (typically a ROI located on the numbers). We think this would fix small drift in long datasets.

**Comment by julou** [comment]
this was my concern at first:
- because it should speed up registration 
- because the number are the most reliable parts of the image to register to

However, I've to admit that in practice using HSR on the whole image as never been a problem for several dozen of datasets. Hence I would give it very low priority, lower than "MoMA rollout to public" :)

**Comment by fjug** [comment]
Ok, thanks for your feedback!
